name: "Test"
description: "Run pytest"
inputs:
  artifact-identifier:
    description: "Unique identifier for uploaded artifacts"
    required: true

runs:
  using: "composite"
  steps:
  - name: Install required dependencies
    shell: bash
    run: |
      python -m pip install --upgrade pip
      pip install .

  - name: test generate minimal deps
    shell: bash
    run: $(which debsbom) -v generate -t spdx -t cdx -o sbom --root tests/root/tree --validate

  - name: Install dev dependencies
    shell: bash
    run: pip install .[dev]

  - name: Run pytest
    env:
      COVERAGE_FILE: .coverage.test.${{ inputs.artifact-identifier }}
    shell: bash
    run: pytest --cov debsbom

  - name: smoke test generate
    shell: bash
    env:
      COVERAGE_FILE: .coverage.smoke-generate.${{ inputs.artifact-identifier }}
    run: |
      coverage run $(which debsbom) -v generate -t spdx -t cdx -o sbom --validate

  - name: upload smoke test SBOMs
    uses: actions/upload-artifact@v4
    with:
      name: sbom-${{ inputs.artifact-identifier }}
      path: |
        sbom.cdx.json
        sbom.spdx.json
      if-no-files-found: error

  - name: Upload coverage data
    uses: actions/upload-artifact@v4
    with:
      name: coverage-data-tests-${{ inputs.artifact-identifier }}
      path: .coverage.*
      include-hidden-files: true
      if-no-files-found: error

