name: "Test"
description: "Run pytest"
inputs:
  artifact-identifier:
    description: "Unique identifier for uploaded artifacts"
    required: true

runs:
  using: "composite"
  steps:
  - name: Install dev dependencies
    shell: bash
    run: |
      python -m pip install --upgrade pip
      pip install .[dev]

  - name: Run pytest
    env:
      COVERAGE_FILE: .coverage.test.${{ inputs.artifact-identifier }}
    shell: bash
    run: pytest --cov debsbom

  - name: smoke test generate
    shell: bash
    env:
      COVERAGE_FILE: .coverage.smoke-generate.${{ inputs.artifact-identifier }}
    run: |
      DISTRO_ARCH="$(dpkg --print-architecture)"
      coverage run $(which debsbom) -v generate --distro-arch $DISTRO_ARCH -t spdx -t cdx -o sbom --validate

  - name: smoke test merge
    shell: bash
    run: |
      export COVERAGE_FILE=".coverage.merge.spdx.${{ inputs.artifact-identifier }}"
      coverage run $(which debsbom) -v merge --validate tests/data/merge-full.spdx.json tests/data/merge-minimal.spdx.json
      export COVERAGE_FILE=".coverage.merge.cdx.${{ inputs.artifact-identifier }}"
      coverage run $(which debsbom) -v merge --validate tests/data/merge-full.cdx.json tests/data/merge-minimal.cdx.json

  - name: test repack flow
    shell: bash
    run: |
      # run repack against known data
      export COVERAGE_FILE=".coverage.generate2.${{ inputs.artifact-identifier }}"
      coverage run $(which debsbom) -v generate -t spdx -o sbom-rp --root tests/root/tree --validate
      export COVERAGE_FILE=".coverage.smoke-download2.${{ inputs.artifact-identifier }}"
      coverage run $(which debsbom) -v download --sources --binaries sbom-rp.spdx.json
      export COVERAGE_FILE=".coverage.smoke-source-merge.${{ inputs.artifact-identifier }}"
      coverage run $(which debsbom) -v source-merge sbom-rp.spdx.json
      export COVERAGE_FILE=".coverage.smoke-repack.${{ inputs.artifact-identifier }}"
      coverage run $(which debsbom) -v repack sbom-rp.spdx.json sbom-rp.repacked.spdx.json
      grep -q "file:///sources/" sbom-rp.repacked.spdx.json
      export COVERAGE_FILE=".coverage.smoke-export.${{ inputs.artifact-identifier }}"
      coverage run $(which debsbom) -v export sbom-rp.spdx.json

  - name: upload smoke test SBOMs
    uses: actions/upload-artifact@v4
    with:
      name: sbom-${{ inputs.artifact-identifier }}
      path: |
        sbom.cdx.json
        sbom.spdx.json
      if-no-files-found: error

  - name: Upload coverage data
    uses: actions/upload-artifact@v4
    with:
      name: coverage-data-tests-${{ inputs.artifact-identifier }}
      path: .coverage.*
      include-hidden-files: true
      if-no-files-found: error

