# Copyright (C) 2025 Siemens
#
# SPDX-License-Identifier: MIT

name: Docs

on:
  push:

jobs:
  docs:
    name: Build Docs
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Build HTML docs
        run: |
          cd docs
          make html
